#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:$PATH"

export EDITOR='subl -w'
export BUNDLER_EDITOR="subl"

# export CUPIDO_HOST="cupido.dev"
export CAP_USER="harm.dewit"
